# Generated by Django 4.0.4 on 2022-04-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0034_rename_name_material_global_material'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MATERIAL_GLOBAL',
            new_name='GLOBAL_MATERIAL',
        ),
    ]
