# Generated by Django 4.0.4 on 2022-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STL',
        ),
    ]
