# Generated by Django 4.0.4 on 2022-04-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_colour_delete_property'),
        ('core', '0002_rename_material_global_global_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COLOUR_GLOBAL',
            new_name='GLOBAL_COLOURS',
        ),
        migrations.RenameModel(
            old_name='GLOBAL_MATERIAL',
            new_name='GLOBAL_MATERIALS',
        ),
    ]
