# Generated by Django 4.0.4 on 2022-04-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_stl'),
        ('core', '0003_rename_colour_global_global_colours_and_more'),
    ]

    operations = [
    ]
