# Generated by Django 4.0.4 on 2022-05-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price_energy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_margin', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tray_length', models.IntegerField()),
                ('tray_width', models.IntegerField()),
                ('tray_height', models.IntegerField()),
                ('power', models.FloatField()),
                ('config', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='vendor.vendor')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
