# Generated by Django 4.0.4 on 2022-04-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_materialcolour_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
