# Generated by Django 4.0.4 on 2022-04-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_alter_materialcolour_price_increase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialColour',
            new_name='MaterialProperties',
        ),
    ]
