# Generated by Django 4.0.4 on 2022-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_rename_materialcolour_materialproperties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrinterMaterial',
        ),
        migrations.AddField(
            model_name='printer',
            name='materials',
            field=models.ManyToManyField(related_name='materials', to='printer.materialproperties'),
        ),
    ]
