# Generated by Django 4.0.4 on 2022-04-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_delete_printermaterial_printer_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATERIAL_GLOBAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Colour',
            new_name='COLOUR_GLOBAL',
        ),
        migrations.RemoveField(
            model_name='material',
            name='density',
        ),
        migrations.AddField(
            model_name='material',
            name='colour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour', to='printer.colour_global'),
        ),
        migrations.AddField(
            model_name='material',
            name='price_increase',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='material',
            name='price_length',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='printer',
            name='materials',
            field=models.ManyToManyField(related_name='materials', to='printer.material'),
        ),
        migrations.DeleteModel(
            name='MaterialProperties',
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='printer.material_global'),
        ),
    ]
