# Generated by Django 4.0.4 on 2022-04-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_material_global_rename_colour_colour_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour', to='printer.colour_global'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='printer.material_global'),
        ),
    ]
