# Generated by Django 4.0.4 on 2022-04-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_alter_material_colour_alter_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='materials',
        ),
    ]
