# Generated by Django 4.0.4 on 2022-04-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_description_vendor_slug_vendor_store_name'),
        ('printer', '0011_material_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='materials',
        ),
        migrations.AddField(
            model_name='material',
            name='printers',
            field=models.ManyToManyField(null=True, related_name='materials', to='printer.printer'),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materials', to='vendor.vendor'),
        ),
    ]
