# Generated by Django 4.0.4 on 2022-04-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_description_vendor_slug_vendor_store_name'),
        ('printer', '0012_remove_material_materials_material_printers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_increase', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('price_length', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour', to='printer.colour_global')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='printer.material_global')),
                ('printers', models.ManyToManyField(null=True, related_name='materials', to='printer.printer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='materials', to='vendor.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
