# Generated by Django 4.0.4 on 2022-04-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0013_materialoptions_delete_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialoptions',
            old_name='name',
            new_name='material',
        ),
    ]
