# Generated by Django 4.0.4 on 2022-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0015_alter_materialoptions_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialoptions',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='materialoptions',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialoptions',
            name='printers',
        ),
        migrations.RemoveField(
            model_name='materialoptions',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='printer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='COLOUR_GLOBAL',
        ),
        migrations.DeleteModel(
            name='MATERIAL_GLOBAL',
        ),
        migrations.DeleteModel(
            name='MaterialOptions',
        ),
    ]
