# Generated by Django 4.0.4 on 2022-04-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('printer', '0016_remove_materialoptions_colour_and_more'),
        ('vendor', '0003_alter_vendor_options_remove_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BooleanField(default=True)),
                ('price_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('price_length', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour', to='core.colour_global')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='core.material_global')),
                ('printers', models.ManyToManyField(null=True, related_name='materials', to='printer.printer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='vendor.vendor')),
            ],
        ),
    ]
