# Generated by Django 4.0.4 on 2022-05-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField(default=True)),
                ('price_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField(default=True)),
                ('price_length', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('global_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='core.global_materials')),
            ],
        ),
    ]
