# Generated by Django 4.0.4 on 2022-05-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('printer', '__first__'),
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_length', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('global_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='core.global_materials')),
                ('printers', models.ManyToManyField(blank=True, related_name='materials', to='printer.printer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='vendor.vendor')),
            ],
            options={
                'unique_together': {('global_material', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField(default=False)),
                ('price_coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('global_colours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour_global', to='core.global_colours')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colours', to='materials.material')),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colours',
                'unique_together': {('global_colours', 'owned_by')},
            },
        ),
    ]
