# Generated by Django 4.0.4 on 2022-05-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        ('materials', '0001_initial'),
        ('printer', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='printers',
            field=models.ManyToManyField(blank=True, related_name='materials', to='printer.printer'),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='colour',
            name='global_colours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour_global', to='core.global_colours'),
        ),
        migrations.AddField(
            model_name='colour',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='materials.material'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('global_material', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('global_colours', 'owned_by')},
        ),
    ]
