# Generated by Django 4.0.4 on 2022-04-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0016_remove_materialoptions_colour_and_more'),
        ('materials', '0002_alter_materialoptions_printers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialoptions',
            name='printers',
            field=models.ManyToManyField(blank=True, related_name='materials', to='printer.printer'),
        ),
    ]
