# Generated by Django 4.0.4 on 2022-06-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='stock',
        ),
    ]
