# Generated by Django 4.0.4 on 2022-04-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0003_alter_materialoptions_printers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialoptions',
            name='price_coefficient',
        ),
        migrations.RemoveField(
            model_name='materialoptions',
            name='colour',
        ),
        migrations.AddField(
            model_name='materialoptions',
            name='colour',
            field=models.ManyToManyField(related_name='colour', to='core.colour_global'),
        ),
    ]
