# Generated by Django 4.0.4 on 2022-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_material_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='price_coefficient',
            field=models.IntegerField(default=0),
        ),
    ]
