# Generated by Django 4.0.4 on 2022-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_rename_material_materialoptions_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='_material',
            new_name='material',
        ),
    ]
