# Generated by Django 4.0.4 on 2022-04-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_rename__material_colour_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='colour',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='colour',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colours', to='materials.materialoptions'),
        ),
    ]
