# Generated by Django 4.0.4 on 2022-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_rename_colour_colour_name_alter_colour_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
