# Generated by Django 4.0.4 on 2022-04-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0007_colour_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour_global', to='core.colour_global'),
        ),
    ]
