# Generated by Django 4.0.4 on 2022-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_colour_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialoptions',
            name='price_coefficient',
        ),
        migrations.AddField(
            model_name='colour',
            name='price_coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
