# Generated by Django 4.0.4 on 2022-04-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_remove_materialoptions_price_coefficient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colours', to='materials.materialoptions'),
        ),
    ]
