# Generated by Django 4.0.4 on 2022-04-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0016_remove_materialoptions_colour_and_more'),
        ('core', '0001_initial'),
        ('vendor', '0018_alter_vendor_slug'),
        ('materials', '0010_alter_colour_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BooleanField(default=True)),
                ('price_length', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='core.material_global')),
                ('printers', models.ManyToManyField(blank=True, related_name='materials', to='printer.printer')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='vendor.vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='colour',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colours', to='materials.material'),
        ),
        migrations.DeleteModel(
            name='MaterialOptions',
        ),
    ]
