# Generated by Django 4.0.4 on 2022-04-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_material_alter_colour_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='stock',
            new_name='stocks',
        ),
    ]
