# Generated by Django 4.0.4 on 2022-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_rename_stock_colour_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='stocks',
        ),
        migrations.AddField(
            model_name='colour',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
