# Generated by Django 4.0.4 on 2022-04-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0018_alter_vendor_slug'),
        ('materials', '0013_remove_colour_stocks_colour_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='vendor.vendor'),
        ),
    ]
