# Generated by Django 4.0.4 on 2022-04-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0017_alter_colour_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colours', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colour_global', to='core.colour_global'),
        ),
    ]
