# Generated by Django 4.0.4 on 2022-04-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0019_alter_colour_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('name', 'material')},
        ),
    ]
