# Generated by Django 4.0.4 on 2022-04-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0020_alter_colour_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='name',
            new_name='colour',
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('colour', 'material')},
        ),
    ]
