# Generated by Django 4.0.4 on 2022-04-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0021_rename_name_colour_colour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='material',
            new_name='owned_material',
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('colour', 'owned_material')},
        ),
    ]
