# Generated by Django 4.0.4 on 2022-04-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0022_rename_material_colour_owned_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='owned_material',
            new_name='owned_by',
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('colour', 'owned_by')},
        ),
    ]
