# Generated by Django 4.0.4 on 2022-04-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0023_rename_owned_material_colour_owned_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='colour',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('name', 'owned_by')},
        ),
    ]
