# Generated by Django 4.0.4 on 2022-04-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0024_rename_colour_colour_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colour',
            new_name='Options',
        ),
    ]
