# Generated by Django 4.0.4 on 2022-04-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0025_rename_colour_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='name',
            new_name='colour',
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together={('colour', 'owned_by')},
        ),
    ]
