# Generated by Django 4.0.4 on 2022-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_rename_name_options_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price_length',
        ),
        migrations.AddField(
            model_name='options',
            name='price_length',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
