# Generated by Django 4.0.4 on 2022-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_remove_material_price_length_options_price_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
