# Generated by Django 4.0.4 on 2022-04-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0029_alter_options_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colours', to='materials.material'),
        ),
    ]
