# Generated by Django 4.0.4 on 2022-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0032_rename_properties_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Material Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price_length',
            new_name='price_coefficient',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.AddField(
            model_name='material',
            name='price_length',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
