# Generated by Django 4.0.4 on 2022-04-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='name',
            new_name='global_material',
        ),
    ]
