# Generated by Django 4.0.4 on 2022-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0035_colour_delete_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colour',
            options={'verbose_name': 'Colour', 'verbose_name_plural': 'Colours'},
        ),
        migrations.AlterField(
            model_name='colour',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
