# Generated by Django 4.0.4 on 2022-04-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_colour_global_global_colours_and_more'),
        ('vendor', '0018_alter_vendor_slug'),
        ('materials', '0036_alter_colour_options_alter_colour_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('global_material', 'vendor')},
        ),
    ]
