"""
Django settings for wemake project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p24)=i4s$=$@$!42$2g@$o5eumo39njlh$(5#3!jao5q$^l#0+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver','127.0.0.1','192.168.0.11','192.168.0.30'] # Remove after debugger+unit tests work

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'vendor_admin'
LOGOUT_REDIRECT_URL = "vendor_login"


SESSION_COOKIE_AGE = 86400 # One day in seconds 
CART_SESSION_ID =  'cart'
# Application definition




INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # Added for debugging.
    'wemake',
    'vendor',
    'printer',
    'core',
    'order',
    'materials',    
    "crispy_forms",
    "crispy_bootstrap5",
    'printPreview',
    'cart',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wemake.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wemake.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.mysql', # <-- UPDATED line 
        'NAME'    : os.environ['DATABASE_NAME'],                 # <-- UPDATED line 
        'USER'    : os.environ['DATABASE_USER'],                     # <-- UPDATED line
        'PASSWORD': os.environ['DATABASE_PASS'],              # <-- UPDATED line
        'HOST'    : os.environ['DATABASE_HOST'],                # <-- UPDATED line
        'PORT'    : os.environ['DATABASE_PORT'],
    },
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

CSRF_USE_SESSIONS = False

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Email Settings:

######## basic python server 
# command (in terimal of development server):  
# python -m smtpd -n -c DebuggingServer 127.0.0.1:1025

# settings:
# EMAIL_HOST = '127.0.0.1'
# EMAIL_PORT = '1025'
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# EMAIL_USE_TLS = False



########'proper' GMail - WeMake server
# settings:

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'make.it.ffra@gmail.com'
EMAIL_HOST_PASSWORD = 'chafhyxogylgnbrg'        # password: 'chafhyxogylgnbrg'  Generated at: https://myaccount.google.com/apppasswords, account: make.it.ffra@gmail.com using 2-factor Authentication. Requires to establish server.connect
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False



# Stripe Settings:

STRIPE_PUBLIC_KEY = "pk_test_51Ia2C5HJurPRv8eSyWlNZ36WmDNj6hFvbuvtVQ6ZzYvPyTn7XrJXcoJeTTxPxzv9NeBSbcV8GIMajn4rbbUW00u300bQN63mbf"
STRIPE_SECRET_KEY = "sk_test_51Ia2C5HJurPRv8eSqT5eKKQaNMmhNfPTy5IUVfzuFWAEw3Hb9M9B6DR6ObJ3EBhZaKuQJNT4zdGv5lbaqFnPsGqj00hPpG7AT4"
STRIPE_WEBHOOK_SECRET = None
