# Generated by Django 4.0.4 on 2022-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('PRINT', 'Printing'), ('DISP', 'Dispatched'), ('DELIV', 'Delivered')], default='PEND', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_paid',
            field=models.CharField(choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('PRINT', 'Printing'), ('DISP', 'Dispatched'), ('DELIV', 'Delivered')], default='NO', max_length=50),
        ),
    ]
