# Generated by Django 4.0.4 on 2022-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='length_of_filament',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='time_to_print',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dim_x',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dim_y',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dim_z',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='infill',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
