# Generated by Django 4.0.4 on 2022-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='price_shipping',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
