# Generated by Django 4.0.4 on 2022-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_slug_order_price_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PRINT', 'Printing'), ('FINISHING', 'Finishing'), ('CMPLT', 'Complete'), ('DELIV', 'Sent')], default='PEDNING', max_length=50),
        ),
    ]
