# Generated by Django 4.0.4 on 2022-05-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_paid',
            field=models.CharField(choices=[('PEND', 'Pending'), ('PRINT', 'Printing'), ('FINISHING', 'Finishing'), ('CMPLT', 'Complete'), ('DELIV', 'Sent')], default='NO', max_length=50),
        ),
    ]
