# Generated by Django 4.0.4 on 2022-05-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_vendor_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_has_been_paid',
        ),
    ]
