# Generated by Django 4.0.4 on 2022-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pending'), ('RECV', 'Received'), ('PRINT', 'Printing'), ('FINISHING', 'Finishing'), ('CMPLT', 'Complete'), ('DELIV', 'Sent')], default='PEDNING', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor_paid',
            field=models.CharField(choices=[('PEND', 'Pending'), ('RECV', 'Received'), ('PRINT', 'Printing'), ('FINISHING', 'Finishing'), ('CMPLT', 'Complete'), ('DELIV', 'Sent')], default='NO', max_length=50),
        ),
    ]
